/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in new projects. It is committed here so
// TypeScript checks work consistently before the first local build.
