import { archiveLandMediaAction, setLandMediaCoverAction, updateLandMediaAction, uploadLandMediaAction } from "@/app/dashboard/land/media-actions";
import { requireDashboardUser } from "@/lib/dashboard/access";

export async function LandMediaPanel({ developmentId, unitId }: { developmentId?: string; unitId?: string }) {
  const { supabase, profile } = await requireDashboardUser();
  const query = supabase.from("land_media").select("id,storage_bucket,storage_path,original_filename,mime_type,file_size,caption,alt_text,is_cover,media_type,visibility,approval_status,rotation,crop_data,created_at").is("archived_at", null).order("sort_order").order("created_at");
  const { data: media } = unitId ? await query.eq("land_unit_id", unitId) : await query.eq("development_id", developmentId!);
  const items = await Promise.all((media || []).map(async (item) => ({ ...item, url: item.mime_type.startsWith("image/") ? (await supabase.storage.from(item.storage_bucket).createSignedUrl(item.storage_path, 300)).data?.signedUrl : undefined })));
  const target = unitId ? { unitId } : { developmentId };
  return <section className="dashboard-panel"><div className="dashboard-section-heading"><div><h2>Media and documents</h2><p>Private storage. Approved candidate media is not public.</p></div></div><form className="dashboard-form" action={uploadLandMediaAction} encType="multipart/form-data"><input type="hidden" name="unitId" value={target.unitId || ""}/><input type="hidden" name="developmentId" value={target.developmentId || ""}/><label>File<input name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></label><label>Media type<select name="mediaType" defaultValue="photo"><option value="photo">Photo</option><option value="site_plan">Site plan</option><option value="map">Map</option><option value="document">PDF document</option></select></label><label>Caption<input name="caption"/></label><label>Alt text<input name="altText"/></label><button className="dashboard-button dashboard-button-primary" type="submit">Upload securely</button></form>{items.length===0?<p className="dashboard-empty-copy">No media or documents uploaded.</p>:<div className="dashboard-media-grid">{items.map(item=><article className="dashboard-media-card" key={item.id}>{item.url?<img src={item.url} alt={item.alt_text||item.caption||item.original_filename} loading="lazy"/>:<div className="dashboard-media-document">PDF</div>}<strong>{item.original_filename}</strong><span>{item.media_type} · {item.approval_status} · {item.visibility}</span>{item.is_cover&&<b>Cover image</b>}<div className="dashboard-media-actions">{item.mime_type.startsWith("image/")&&profile.role!=="viewer"&&<form action={setLandMediaCoverAction}><input type="hidden" name="mediaId" value={item.id}/><button className="dashboard-button dashboard-button-secondary">Set cover</button></form>}{profile.role==="administrator"||profile.role==="staff"?<><form action={updateLandMediaAction}><input type="hidden" name="mediaId" value={item.id}/><input name="caption" defaultValue={item.caption||""} placeholder="Caption"/><input name="altText" defaultValue={item.alt_text||""} placeholder="Alt text"/><select name="visibility" defaultValue={item.visibility}><option>internal</option><option>public_candidate</option></select><select name="approval" defaultValue={item.approval_status}><option>pending</option><option>approved</option><option>rejected</option></select><input name="rotation" type="number" min="0" max="359" defaultValue={item.rotation}/><input name="zoom" type="number" min="1" max="3" step="0.1" defaultValue={Number((item.crop_data as {zoom?:number})?.zoom||1)}/><button className="dashboard-button dashboard-button-secondary">Save edit metadata</button></form><form action={archiveLandMediaAction}><input type="hidden" name="mediaId" value={item.id}/><button className="dashboard-button dashboard-button-danger">Archive</button></form></>:null}</div></article>)}</div>}</section>;
}
