"use server";
import type { Enums } from "@/lib/supabase/database.types";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireRoles } from "@/lib/dashboard/access";
const s=(f:FormData,k:string)=>String(f.get(k)||"").trim();
export async function createDevelopmentAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const {data,error}=await supabase.rpc("create_land_development",{new_name:s(form,"name"),new_slug:s(form,"slug"),new_development_type:s(form,"developmentType"),new_location:s(form,"location"),new_description:s(form,"description")||undefined,new_address:s(form,"address")||undefined,new_city_town:s(form,"cityTown")||undefined,new_province:s(form,"province")||undefined,new_total_land_size:form.get("size")?Number(form.get("size")):undefined,new_land_size_unit:s(form,"sizeUnit")||undefined,new_internal_notes:s(form,"internalNotes")||undefined});if(error||!data) redirect(`/dashboard/land/developments/new?error=${encodeURIComponent(error?.message||"Could not create development")}`);revalidatePath("/dashboard/land");revalidatePath("/dashboard/land/developments");redirect(`/dashboard/land/developments/${(data as {id:string}).id}`)}
export async function createUnitAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const {data,error}=await supabase.rpc("create_land_unit",{new_development_id:s(form,"developmentId"),new_stand_number:s(form,"standNumber"),new_slug:s(form,"slug"),new_property_type:s(form,"propertyType") as Enums<"land_unit_property_type">,new_land_size:Number(form.get("size")),new_land_size_unit:s(form,"sizeUnit"),new_title:s(form,"title")||undefined,new_description:s(form,"description")||undefined,new_location_description:s(form,"location")||undefined,new_asking_price:form.get("price")?Number(form.get("price")):undefined,new_currency:s(form,"currency")||"USD",new_internal_notes:s(form,"internalNotes")||undefined});if(error||!data) redirect(`/dashboard/land/units/new?error=${encodeURIComponent(error?.message||"Could not create land unit")}`);revalidatePath("/dashboard/land");revalidatePath("/dashboard/land/units");redirect(`/dashboard/land/units/${(data as {id:string}).id}`)}
export async function updateDevelopmentAction(id:string,form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const {error}=await supabase.rpc("update_land_development",{target_id:id,new_name:s(form,"name"),new_slug:s(form,"slug"),new_development_type:s(form,"developmentType"),new_location:s(form,"location"),new_description:s(form,"description")||undefined,new_address:s(form,"address")||undefined,new_city_town:s(form,"cityTown")||undefined,new_province:s(form,"province")||undefined,new_total_land_size:form.get("size")?Number(form.get("size")):undefined,new_land_size_unit:s(form,"sizeUnit")||undefined,new_internal_notes:s(form,"internalNotes")||undefined,new_status:s(form,"status") as Enums<"land_development_status">});if(error)redirect(`/dashboard/land/developments/${id}/edit?error=${encodeURIComponent(error.message)}`);revalidatePath(`/dashboard/land/developments/${id}`);redirect(`/dashboard/land/developments/${id}`)}
export async function updateUnitAction(id:string,form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const {error}=await supabase.rpc("update_land_unit",{target_id:id,new_stand_number:s(form,"standNumber"),new_slug:s(form,"slug"),new_property_type:s(form,"propertyType") as Enums<"land_unit_property_type">,new_land_size:Number(form.get("size")),new_land_size_unit:s(form,"sizeUnit"),new_title:s(form,"title")||undefined,new_description:s(form,"description")||undefined,new_location_description:s(form,"location")||undefined,new_asking_price:form.get("price")?Number(form.get("price")):undefined,new_currency:s(form,"currency")||"USD",new_internal_notes:s(form,"internalNotes")||undefined,new_availability_status:s(form,"availability") as Enums<"land_unit_availability_status">,new_verification_status:s(form,"verification") as Enums<"land_unit_verification_status">});if(error)redirect(`/dashboard/land/units/${id}/edit?error=${encodeURIComponent(error.message)}`);revalidatePath(`/dashboard/land/units/${id}`);revalidatePath("/dashboard/land/units");redirect(`/dashboard/land/units/${id}`)}
