"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireRoles } from "@/lib/dashboard/access";
import type { Enums } from "@/lib/supabase/database.types";
const text=(f:FormData,k:string)=>String(f.get(k)||"").trim();
const safeName=(name:string)=>name.toLowerCase().replace(/[^a-z0-9._-]+/g,"-").slice(-120);
const targetPath=(developmentId?:string,unitId?:string)=>`/dashboard/land/${unitId?`units/${unitId}`:`developments/${developmentId}`}`;
export async function uploadLandMediaAction(form:FormData){
  const {supabase,profile}=await requireRoles(["administrator","staff"]); const developmentId=text(form,"developmentId")||undefined; const unitId=text(form,"unitId")||undefined; const file=form.get("file"); const back=targetPath(developmentId,unitId);
  if(!(file instanceof File)||file.size===0) redirect(`${back}?error=Choose+a+file`);
  const isDocument=file.type==="application/pdf"; const valid=isDocument?file.size<=15*1024*1024&&text(form,"mediaType")==="document":["image/jpeg","image/png","image/webp"].includes(file.type)&&file.size<=10*1024*1024;
  if(!valid) redirect(`${back}?error=Unsupported+file+type+or+size`);
  const bucket=isDocument?"land-documents":"land-media"; const path=`${unitId?`units/${unitId}`:`developments/${developmentId}`}/${crypto.randomUUID()}-${safeName(file.name)}`;
  const uploaded=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false}); if(uploaded.error) redirect(`${back}?error=Upload+failed`);
  const {data,error}=await supabase.from("land_media").insert({development_id:developmentId||null,land_unit_id:unitId||null,media_type:(isDocument?"other_document":text(form,"mediaType")||"photo") as Enums<"land_media_type">,storage_bucket:bucket,storage_path:path,original_filename:file.name,mime_type:file.type,file_size:file.size,caption:text(form,"caption")||null,alt_text:text(form,"altText")||null,created_by:profile.id,updated_by:profile.id}).select("id").single();
  if(error||!data){await supabase.storage.from(bucket).remove([path]);redirect(`${back}?error=Media+record+failed`)} revalidatePath(back); redirect(`${back}?message=Media+uploaded`);
}
export async function setLandMediaCoverAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const {data:m}=await supabase.from("land_media").select("id,development_id,land_unit_id,mime_type,archived_at").eq("id",id).maybeSingle();if(!m||m.archived_at||!m.mime_type.startsWith("image/"))return;await supabase.from("land_media").update({is_cover:false}).match(m.development_id?{development_id:m.development_id}:{land_unit_id:m.land_unit_id});await supabase.from("land_media").update({is_cover:true}).eq("id",id);revalidatePath(targetPath(m.development_id||undefined,m.land_unit_id||undefined));}
export async function archiveLandMediaAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const {data:m}=await supabase.from("land_media").select("id,development_id,land_unit_id").eq("id",id).maybeSingle();if(m){await supabase.from("land_media").update({archived_at:new Date().toISOString(),is_cover:false}).eq("id",id);revalidatePath(targetPath(m.development_id||undefined,m.land_unit_id||undefined));}}
export async function updateLandMediaAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const {data:m}=await supabase.from("land_media").select("development_id,land_unit_id").eq("id",id).maybeSingle();if(!m)redirect("/dashboard/land");const {error}=await supabase.from("land_media").update({caption:text(form,"caption")||null,alt_text:text(form,"altText")||null,visibility:text(form,"visibility") as Enums<"land_media_visibility">,approval_status:text(form,"approval") as Enums<"land_media_approval">,rotation:Math.max(0,Math.min(359,Number(form.get("rotation")||0))),crop_data:{zoom:Number(form.get("zoom")||1),x:Number(form.get("x")||0),y:Number(form.get("y")||0)}}).eq("id",id);if(error)redirect(`${targetPath(m.development_id||undefined,m.land_unit_id||undefined)}?error=Media+update+failed`);revalidatePath(targetPath(m.development_id||undefined,m.land_unit_id||undefined));}
export async function reorderLandMediaAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const order=Number(form.get("sortOrder")||0);const {data:m}=await supabase.from("land_media").select("development_id,land_unit_id").eq("id",id).maybeSingle();if(m)await supabase.from("land_media").update({sort_order:Math.max(0,Math.floor(order))}).eq("id",id);if(m)revalidatePath(targetPath(m.development_id||undefined,m.land_unit_id||undefined));}
export async function moveLandMediaAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const direction=Number(form.get("direction")||0);const {data:item}=await supabase.from("land_media").select("id,sort_order,development_id,land_unit_id").eq("id",id).maybeSingle();if(!item||![-1,1].includes(direction))return;const query=supabase.from("land_media").select("id,sort_order").is("archived_at",null).order("sort_order").order("created_at");const rows=item.development_id?await query.eq("development_id",item.development_id):await query.eq("land_unit_id",item.land_unit_id!);const list=rows.data||[];const index=list.findIndex(row=>row.id===id);const other=list[index+direction];if(other){await supabase.from("land_media").update({sort_order:other.sort_order}).eq("id",item.id);await supabase.from("land_media").update({sort_order:item.sort_order}).eq("id",other.id);}revalidatePath(targetPath(item.development_id||undefined,item.land_unit_id||undefined));}
export async function replaceLandMediaAction(form:FormData){const {supabase,profile}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const file=form.get("file");if(!(file instanceof File)||file.size===0)return;const {data:old}=await supabase.from("land_media").select("id,storage_bucket,storage_path,development_id,land_unit_id,mime_type").eq("id",id).maybeSingle();if(!old||!file.type.startsWith("image/")||!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>10*1024*1024)return;const path=`${old.land_unit_id?`units/${old.land_unit_id}`:old.development_id?`developments/${old.development_id}`:"replacements"}/${crypto.randomUUID()}-${safeName(file.name)}`;const uploaded=await supabase.storage.from("land-media").upload(path,file,{contentType:file.type,upsert:false});if(uploaded.error)return;const result=await supabase.from("land_media").update({storage_bucket:"land-media",storage_path:path,original_filename:file.name,mime_type:file.type,file_size:file.size,updated_by:profile.id,rotation:0,crop_data:{zoom:1,x:0,y:0}}).eq("id",id);if(result.error){await supabase.storage.from("land-media").remove([path]);return;}await supabase.storage.from(old.storage_bucket).remove([old.storage_path]);revalidatePath(targetPath(old.development_id||undefined,old.land_unit_id||undefined));}
export async function getLandMediaUrlAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff","accountant","viewer"]);const id=text(form,"mediaId");const {data:item}=await supabase.from("land_media").select("storage_bucket,storage_path,development_id,land_unit_id").eq("id",id).is("archived_at",null).maybeSingle();if(!item)return;const signed=await supabase.storage.from(item.storage_bucket).createSignedUrl(item.storage_path,300);if(signed.data?.signedUrl)redirect(signed.data.signedUrl);}
