"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireRoles } from "@/lib/dashboard/access";
import type { Enums } from "@/lib/supabase/database.types";
const text=(f:FormData,k:string)=>String(f.get(k)||"").trim();
const safeName=(name:string)=>name.toLowerCase().replace(/[^a-z0-9._-]+/g,"-").slice(-120);
const targetPath=(developmentId?:string,unitId?:string)=>`/dashboard/land/${unitId?`units/${unitId}`:`developments/${developmentId}`}`;
export async function uploadLandMediaAction(form:FormData){
  const {supabase,profile}=await requireRoles(["administrator","staff"]); const developmentId=text(form,"developmentId")||undefined; const unitId=text(form,"unitId")||undefined; const file=form.get("file"); const back=targetPath(developmentId,unitId);
  if(!(file instanceof File)||file.size===0) redirect(`${back}?error=Choose+a+file`);
  const isDocument=file.type==="application/pdf"; const valid=isDocument?file.size<=15*1024*1024&&text(form,"mediaType")==="document":["image/jpeg","image/png","image/webp"].includes(file.type)&&file.size<=10*1024*1024;
  if(!valid) redirect(`${back}?error=Unsupported+file+type+or+size`);
  const bucket=isDocument?"land-documents":"land-media"; const path=`${unitId?`units/${unitId}`:`developments/${developmentId}`}/${crypto.randomUUID()}-${safeName(file.name)}`;
  const uploaded=await supabase.storage.from(bucket).upload(path,file,{contentType:file.type,upsert:false}); if(uploaded.error) redirect(`${back}?error=Upload+failed`);
  const {data,error}=await supabase.from("land_media").insert({development_id:developmentId||null,land_unit_id:unitId||null,media_type:(isDocument?"other_document":text(form,"mediaType")||"photo") as Enums<"land_media_type">,storage_bucket:bucket,storage_path:path,original_filename:file.name,mime_type:file.type,file_size:file.size,caption:text(form,"caption")||null,alt_text:text(form,"altText")||null,created_by:profile.id,updated_by:profile.id}).select("id").single();
  if(error||!data){await supabase.storage.from(bucket).remove([path]);redirect(`${back}?error=Media+record+failed`)} revalidatePath(back); redirect(`${back}?message=Media+uploaded`);
}
export async function setLandMediaCoverAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const {data:m}=await supabase.from("land_media").select("id,development_id,land_unit_id").eq("id",id).maybeSingle();if(!m)redirect("/dashboard/land");await supabase.from("land_media").update({is_cover:false}).match(m.development_id?{development_id:m.development_id}:{land_unit_id:m.land_unit_id});await supabase.from("land_media").update({is_cover:true}).eq("id",id);revalidatePath(targetPath(m.development_id||undefined,m.land_unit_id||undefined));}
export async function archiveLandMediaAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const {data:m}=await supabase.from("land_media").select("id,development_id,land_unit_id").eq("id",id).maybeSingle();if(m){await supabase.from("land_media").update({archived_at:new Date().toISOString(),is_cover:false}).eq("id",id);revalidatePath(targetPath(m.development_id||undefined,m.land_unit_id||undefined));}}
export async function updateLandMediaAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const {data:m}=await supabase.from("land_media").select("development_id,land_unit_id").eq("id",id).maybeSingle();if(!m)redirect("/dashboard/land");const {error}=await supabase.from("land_media").update({caption:text(form,"caption")||null,alt_text:text(form,"altText")||null,visibility:text(form,"visibility") as Enums<"land_media_visibility">,approval_status:text(form,"approval") as Enums<"land_media_approval">,rotation:Math.max(0,Math.min(359,Number(form.get("rotation")||0))),crop_data:{zoom:Number(form.get("zoom")||1),x:Number(form.get("x")||0),y:Number(form.get("y")||0)}}).eq("id",id);if(error)redirect(`${targetPath(m.development_id||undefined,m.land_unit_id||undefined)}?error=Media+update+failed`);revalidatePath(targetPath(m.development_id||undefined,m.land_unit_id||undefined));}
export async function reorderLandMediaAction(form:FormData){const {supabase}=await requireRoles(["administrator","staff"]);const id=text(form,"mediaId");const order=Number(form.get("sortOrder")||0);const {data:m}=await supabase.from("land_media").select("development_id,land_unit_id").eq("id",id).maybeSingle();if(m)await supabase.from("land_media").update({sort_order:Math.max(0,Math.floor(order))}).eq("id",id);if(m)revalidatePath(targetPath(m.development_id||undefined,m.land_unit_id||undefined));}
